language: c
sudo: required
dist: trusty

addons:
  apt:
    packages:
      - python-pip
      - openssl

install:
  - pip install asn1crypto --user
  - sudo apt-add-repository -y ppa:team-gcc-arm-embedded/ppa
  - sudo apt-get update
  - sudo apt-get install -yy gcc-arm-embedded

script:
  - 'cd u2f'
  - 'make'
  - 'make clean certclean'
  - 'make'
  - 'openssl ecparam -name prime256v1 -genkey -noout -outform der -out key.der'
  - './inject_key.py --key key.der --ctr 1001'
  - 'cd ..'
